import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/shared/navbar/Navbar';
import { ToastContainer } from 'react-toastify'; 
import Provider from "@/app/lib/providers/index";
// import TimelineProvider from '@/context/timelinecontext';
import Footer from "@/components/shared/footer/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
         <Provider>
          
           <Navbar></Navbar>
            {children}
            <ToastContainer position="top-right" /> 
       
            <Footer></Footer>
            
         </Provider>
        
         

{/*         
       <Navbar></Navbar>
        {children}
       <ToastContainer position="top-right" /> 
        <h2 className="bg-blue-300"> Footer </h2> */}
        
        </body>
    </html>
  );
}
